/**
 * xa11y — Cross-platform accessibility client library for Node.js.
 *
 * @example
 * ```ts
 * import { App } from '@xa11y/xa11y';
 *
 * const app = await App.byName('Safari');
 * await app.locator('button[name="OK"]').press();
 *
 * for (const btn of await app.locator('button').elements()) {
 *   console.log(btn.name);
 * }
 * ```
 *
 * @packageDocumentation
 */

// Re-export every class, interface, and function generated from the Rust
// source. The canonical signatures live in `native.d.ts`, which is
// auto-generated by napi-rs and post-processed by
// `scripts/patch-native-dts.mjs` to narrow a couple of literal types.
// This means: if you change the Rust API, the TS types follow automatically —
// only the JS-only symbols below need hand maintenance.
export * from './native.js';

// ── JS-only: typed error hierarchy ─────────────────────────────────────────
//
// The Rust side throws plain napi errors; the wrapper in `index.js`
// re-throws them as the following subclasses so consumers can narrow with
// `instanceof`. These don't exist on the Rust side at all.

/** Base class for all xa11y errors. */
export class XA11yError extends Error {}

/** Accessibility permissions have not been granted. */
export class PermissionDeniedError extends XA11yError {}

/** No element matched the selector (also used for stale elements). */
export class SelectorNotMatchedError extends XA11yError {}

/** The requested action is not supported on the target element. */
export class ActionNotSupportedError extends XA11yError {}

/** An operation exceeded its timeout. */
export class TimeoutError extends XA11yError {}

/** The selector string has invalid syntax or the action data was rejected. */
export class InvalidSelectorError extends XA11yError {}

/** An OS-level accessibility error occurred. */
export class PlatformError extends XA11yError {}

// ── JS-only: EventType constants object ────────────────────────────────────
//
// The `EventTypeName` string-literal union is defined in `native.d.ts` (added
// by the patch script). `EventType` is an enum-like frozen object exposed
// only from JS — purely a convenience for consumers who prefer named
// constants to string literals.

/**
 * Enum-like frozen object listing all accessibility event type names.
 * Using these constants is equivalent to writing the string literal, but
 * gives autocomplete and avoids typos.
 */
export const EventType: Readonly<Record<
  | 'FocusChanged'
  | 'ValueChanged'
  | 'NameChanged'
  | 'StateChanged'
  | 'StructureChanged'
  | 'WindowOpened'
  | 'WindowClosed'
  | 'WindowActivated'
  | 'WindowDeactivated'
  | 'SelectionChanged'
  | 'MenuOpened'
  | 'MenuClosed'
  | 'Alert'
  | 'TextChanged',
  EventTypeName
>>;

// Forward-declared here so the generic parameter above can reference it
// even though its authoritative definition lives in native.d.ts.
type EventTypeName = import('./native.js').EventTypeName;
