// Declarations in `index.d.ts` / `native.d.ts` must match what actually
// exists at runtime, in both directions.
//
// This is the JS counterpart of `xa11y-python/tests/test_typing.py`. The
// bindings-parity check (`cargo xtask check-bindings-parity`) compares core
// against the *Rust* source of each binding; nothing else verified that the
// TypeScript declarations describe the objects `index.js` really exports. A
// drifted declaration is invisible to `tsc` — it type-checks fine against
// itself — but breaks consumers at runtime and ships wrong API docs, exactly
// how `App.find` shipped undocumented on the Python side.
//
// The declarations are scanned rather than parsed with the TypeScript
// compiler API: `typescript` 7 is the native port and no longer exposes one.
// The scanner is the same brace/paren-depth approach `index_dts_members` in
// xtask/src/binding_api.rs uses on these files, and both `.d.ts` files are
// either generated or written in a consistent style.
//
// `native.d.ts` is generated by `napi build` and gitignored, so this test
// requires a build first (`cargo xtask test-js` does that for you).

'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const { EventEmitter } = require('node:events');
const { readFileSync, existsSync } = require('node:fs');
const { join } = require('node:path');

const xa11y = require('../../index.js');

const ROOT = join(__dirname, '..', '..');

/** Read a `.d.ts` with comments stripped, preserving line structure. */
function readDts(file) {
  const path = join(ROOT, file);
  assert.ok(
    existsSync(path),
    `${file} is missing — run \`npm run build\` (or \`cargo xtask test-js\`) first`,
  );
  const source = readFileSync(path, 'utf8');
  // Doc comments carry `@example` blocks full of real-looking code; dropping
  // them first keeps the scanner from reading examples as declarations.
  return source
    .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '))
    .split('\n')
    .map((line) => (line.trim().startsWith('//') ? '' : line));
}

const CLASS_HEADER =
  /^\s*(?:export\s+)?(?:declare\s+)?(?:abstract\s+)?(class|interface)\s+([A-Za-z_$][\w$]*)/;
const MEMBER =
  /^(?:(static)\s+)?(?:readonly\s+)?(?:(?:get|set)\s+)?([A-Za-z_$][\w$]*)\s*\??\s*([(<:])/;

function countDepth(line, open, close) {
  let n = 0;
  for (const ch of line) {
    if (ch === open) n += 1;
    else if (ch === close) n -= 1;
  }
  return n;
}

/**
 * Collect declared members of every class and interface, merged by name so a
 * `declare module './native.js' { interface Locator { ... } }` augmentation
 * lands on the same entry as the generated class.
 *
 * Members are split three ways because only two of them exist on the runtime
 * *class*: methods and accessors live on the prototype (or the constructor,
 * when static), while plain property declarations describe instance fields
 * assigned in a constructor — `TimeoutError.elapsedMs` and friends — which no
 * amount of introspection on the class can see.
 */
function declaredTypes(files, wantKind) {
  const types = new Map();
  const entry = (name) => {
    if (!types.has(name)) {
      types.set(name, { instance: new Set(), static: new Set(), properties: new Set() });
    }
    return types.get(name);
  };

  for (const file of files) {
    const lines = readDts(file);
    for (let i = 0; i < lines.length; i += 1) {
      const header = CLASS_HEADER.exec(lines[i]);
      if (!header) continue;
      if (wantKind && header[1] !== wantKind) continue;
      const decl = entry(header[2]);

      // The opening brace may sit on a later line for a wrapped `extends`.
      let k = i;
      while (k < lines.length && !lines[k].includes('{')) k += 1;
      if (k >= lines.length) continue;
      let braces = countDepth(lines[k], '{', '}');
      let parens = countDepth(lines[k], '(', ')');

      for (k += 1; k < lines.length && braces > 0; k += 1) {
        const atMemberLevel = braces === 1 && parens === 0;
        braces += countDepth(lines[k], '{', '}');
        parens += countDepth(lines[k], '(', ')');
        // A member sits at brace depth 1 and outside any wrapped signature,
        // so a multi-line parameter list isn't read as members named after
        // its parameters.
        if (!atMemberLevel) continue;
        const member = MEMBER.exec(lines[k].trim());
        if (!member) continue;
        const [, isStatic, name, kind] = member;
        if (name === 'constructor') continue;
        if (kind === ':') decl.properties.add(name);
        else (isStatic ? decl.static : decl.instance).add(name);
      }
      i = Math.max(k - 1, i);
    }
  }
  return types;
}

/**
 * Value names the package declares at module level: classes, functions, and
 * value re-exports from `./native.js`. Type-only exports
 * (`export type { Rect }`) are excluded — they have no runtime counterpart by
 * design.
 *
 * Only `index.d.ts` is read: it defines the package's public entry point,
 * while `native.d.ts` describes the internal napi module that `index.js`
 * re-exports selectively.
 */
function declaredModuleNames() {
  const names = new Set();
  const lines = readDts('index.d.ts');
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    const decl = /^export\s+(?:declare\s+)?(?:class|function)\s+([A-Za-z_$][\w$]*)/.exec(line);
    if (decl) {
      names.add(decl[1]);
      continue;
    }
    if (!/^export\s*\{/.test(line)) continue;
    // `export { A, B } from './native.js';`, possibly spread over lines.
    let block = '';
    for (let k = i; k < lines.length; k += 1) {
      block += lines[k];
      if (lines[k].includes('}')) {
        i = k;
        break;
      }
    }
    for (const spec of block.slice(block.indexOf('{') + 1, block.indexOf('}')).split(',')) {
      const name = spec.trim().split(/\s+as\s+/).pop().trim();
      if (name && !name.startsWith('type ') && isPublic(name)) names.add(name);
    }
  }
  return names;
}

// ── Runtime introspection ──────────────────────────────────────────────────

/**
 * Own property names along `obj`'s prototype chain, stopping before any of
 * `stops`. Walking the chain is what makes this meaningful for `App` and
 * `Subscription`, whose JS wrappers extend a napi class: the inherited half
 * of the surface is just as public as the wrapper's own half.
 */
function chainMembers(obj, stops) {
  const out = new Set();
  for (let cur = obj; cur && !stops.includes(cur); cur = Object.getPrototypeOf(cur)) {
    for (const key of Object.getOwnPropertyNames(cur)) out.add(key);
  }
  return out;
}

/** Underscore-prefixed names are internal by convention, as in Python. */
const isPublic = (name) => !name.startsWith('_');

const INSTANCE_STOPS = [Object.prototype, Error.prototype, EventEmitter.prototype];
// `Error` and `EventEmitter` carry their own statics (`captureStackTrace`,
// `defaultMaxListeners`, ...) that a subclass inherits but does not declare.
const STATIC_STOPS = [Function.prototype, Error, EventEmitter];
// `arguments` and `caller` are legacy own properties of every function
// object, not API.
const FUNCTION_STATICS = new Set(['length', 'name', 'prototype', 'arguments', 'caller']);

function runtimeMembers(cls) {
  const instance = new Set(
    [...chainMembers(cls.prototype, INSTANCE_STOPS)].filter(
      (n) => n !== 'constructor' && isPublic(n),
    ),
  );
  const statics = new Set(
    [...chainMembers(cls, STATIC_STOPS)].filter((n) => !FUNCTION_STATICS.has(n) && isPublic(n)),
  );
  return { instance, statics };
}

/**
 * The declaration a *consumer* sees for each name, paired with the runtime
 * class it describes.
 *
 * `index.d.ts` is the package's `types` entry, so where it declares a class
 * of its own — `App`, the EventEmitter `Subscription`, the error hierarchy —
 * that declaration is what consumers get, and the napi class of the same name
 * in `native.d.ts` is shadowed. Merging the two would let a member declared
 * only on the shadowed class hide the fact that consumers cannot see it.
 * Interface declarations are augmentations
 * (`declare module './native.js' { interface Locator { ... } }`) and do merge.
 */
function consumerDeclarations() {
  const merged = declaredTypes(['native.d.ts'], 'class');
  for (const [name, decl] of declaredTypes(['index.d.ts'], 'class')) merged.set(name, decl);
  for (const [name, decl] of declaredTypes(['index.d.ts'], 'interface')) {
    const into = merged.get(name);
    if (!into) {
      merged.set(name, decl);
      continue;
    }
    for (const key of ['instance', 'static', 'properties']) {
      for (const member of decl[key]) into[key].add(member);
    }
  }
  return merged;
}

/** Exported classes, paired with the declaration entry of the same name. */
function declaredClassesWithRuntime() {
  const types = consumerDeclarations();
  const pairs = [];
  for (const [name, decl] of types) {
    const cls = xa11y[name];
    if (typeof cls !== 'function' || !cls.prototype) continue;
    pairs.push({ name, decl, cls });
  }
  return pairs;
}

// ── Tests ──────────────────────────────────────────────────────────────────

test('the scan finds the declarations it is meant to check', () => {
  // Without this, a scanner that silently matched nothing would make every
  // other test in this file pass vacuously.
  const found = new Map(declaredClassesWithRuntime().map((p) => [p.name, p.decl]));
  for (const [type, statics, instance] of [
    ['App', ['byName', 'byPid', 'foreground', 'list', 'find'], ['locator', 'subscribe', 'name']],
    ['Element', [], ['press', 'tree', 'enabled']],
    ['InputSim', [], ['click', 'drag', 'keyDown', 'keyUp', 'mouseDown', 'mouseUp']],
    ['Locator', [], ['press', 'element', 'waitUntil']],
    ['Subscription', [], ['close', 'waitForEvent']],
  ]) {
    const decl = found.get(type);
    assert.ok(decl, `scanner did not find class ${type}: ${[...found.keys()]}`);
    for (const name of statics) {
      assert.ok(decl.static.has(name), `scanner did not find static ${type}.${name}`);
    }
    for (const name of instance) {
      assert.ok(decl.instance.has(name), `scanner did not find ${type}.prototype.${name}`);
    }
  }
});

test('every declared class member exists at runtime', () => {
  const missing = [];
  for (const { name, decl, cls } of declaredClassesWithRuntime()) {
    for (const member of decl.instance) {
      if (!(member in cls.prototype)) missing.push(`${name}.prototype.${member}`);
    }
    for (const member of decl.static) {
      if (!(member in cls)) missing.push(`${name}.${member}`);
    }
  }
  assert.deepEqual(
    missing.sort(),
    [],
    'the .d.ts declares members the runtime lacks — consumers calling them get ' +
      '"is not a function" despite a clean tsc run',
  );
});

test('every runtime class member is declared', () => {
  const undeclared = [];
  for (const { name, decl, cls } of declaredClassesWithRuntime()) {
    const { instance, statics } = runtimeMembers(cls);
    for (const member of instance) {
      if (!decl.instance.has(member) && !decl.properties.has(member)) {
        undeclared.push(`${name}.prototype.${member}`);
      }
    }
    for (const member of statics) {
      if (!decl.static.has(member) && !decl.properties.has(member)) {
        undeclared.push(`${name}.${member}`);
      }
    }
  }
  assert.deepEqual(
    undeclared.sort(),
    [],
    'runtime members missing from the .d.ts — they are invisible to type ' +
      'checkers, IDEs, and the generated API docs',
  );
});

test('module-level exports and declarations agree', () => {
  const declared = declaredModuleNames();
  const runtime = new Set(Object.keys(xa11y).filter(isPublic));

  const missingFromDts = [...runtime].filter((n) => !declared.has(n)).sort();
  const staleInDts = [...declared].filter((n) => !runtime.has(n)).sort();

  assert.deepEqual(missingFromDts, [], 'exports missing from index.d.ts');
  assert.deepEqual(staleInDts, [], 'index.d.ts declares exports index.js lacks');
});

test('the narrowed input-layer types survive the build', () => {
  // `MouseButtonName` / `AnchorName` are injected by
  // scripts/patch-native-dts.mjs, which is easy to forget when adding a new
  // string-valued input parameter. Assert the narrowings are still there
  // rather than silently widened back to `string`.
  const native = readFileSync(join(ROOT, 'native.d.ts'), 'utf8');
  for (const decl of [
    "export type MouseButtonName = 'left' | 'right' | 'middle';",
    'export type AnchorName =',
    '  button?: MouseButtonName',
    '  anchor?: AnchorName | [number, number]',
    '  mouseDown(button?: MouseButtonName | undefined | null): Promise<void>',
  ]) {
    assert.ok(native.includes(decl), `native.d.ts is missing: ${decl}`);
  }
});
