"""Type stubs for the native xa11y extension module."""

from enum import IntEnum
from typing import Optional

class Role(IntEnum):
    Unknown = 0
    Window = 1
    Application = 2
    Button = 3
    CheckBox = 4
    RadioButton = 5
    TextField = 6
    TextArea = 7
    StaticText = 8
    ComboBox = 9
    List = 10
    ListItem = 11
    Menu = 12
    MenuItem = 13
    MenuBar = 14
    Tab = 15
    TabGroup = 16
    Table = 17
    TableRow = 18
    TableCell = 19
    Toolbar = 20
    ScrollBar = 21
    Slider = 22
    Image = 23
    Link = 24
    Group = 25
    Dialog = 26
    Alert = 27
    ProgressBar = 28
    TreeItem = 29
    WebArea = 30
    Heading = 31
    Separator = 32
    SplitGroup = 33
    Switch = 34
    SpinButton = 35
    Tooltip = 36
    Status = 37
    Navigation = 38

class Action(IntEnum):
    Press = 0
    Focus = 1
    SetValue = 2
    Toggle = 3
    Expand = 4
    Collapse = 5
    Select = 6
    ShowMenu = 7
    ScrollIntoView = 8
    Scroll = 9
    Increment = 10
    Decrement = 11
    Blur = 12
    SetTextSelection = 13
    TypeText = 14

class ScrollDirection(IntEnum):
    Up = 0
    Down = 1
    Left = 2
    Right = 3

class Toggled(IntEnum):
    Off = 0
    On = 1
    Mixed = 2

class Rect:
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...

class NormalizedRect:
    @property
    def left(self) -> float: ...
    @property
    def top(self) -> float: ...
    @property
    def right(self) -> float: ...
    @property
    def bottom(self) -> float: ...

class StateSet:
    @property
    def enabled(self) -> bool: ...
    @property
    def visible(self) -> bool: ...
    @property
    def focused(self) -> bool: ...
    @property
    def checked(self) -> Optional[Toggled]: ...
    @property
    def selected(self) -> bool: ...
    @property
    def expanded(self) -> Optional[bool]: ...
    @property
    def editable(self) -> bool: ...
    @property
    def focusable(self) -> bool: ...
    @property
    def modal(self) -> bool: ...
    @property
    def required(self) -> bool: ...
    @property
    def busy(self) -> bool: ...

class Node:
    @property
    def role(self) -> Role: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def value(self) -> Optional[str]: ...
    @property
    def description(self) -> Optional[str]: ...
    @property
    def bounds(self) -> Optional[Rect]: ...
    @property
    def bounds_normalized(self) -> Optional[NormalizedRect]: ...
    @property
    def actions(self) -> list[Action]: ...
    @property
    def states(self) -> StateSet: ...
    @property
    def depth(self) -> int: ...
    @property
    def numeric_value(self) -> Optional[float]: ...
    @property
    def min_value(self) -> Optional[float]: ...
    @property
    def max_value(self) -> Optional[float]: ...
    @property
    def stable_id(self) -> Optional[str]: ...

class AppInfo:
    @property
    def name(self) -> str: ...
    @property
    def pid(self) -> int: ...
    @property
    def bundle_id(self) -> Optional[str]: ...

class QueryOptions:
    max_depth: Optional[int]
    max_elements: Optional[int]
    visible_only: bool
    include_raw: bool
    def __init__(
        self,
        *,
        max_depth: Optional[int] = None,
        max_elements: Optional[int] = None,
        visible_only: bool = False,
        include_raw: bool = False,
    ) -> None: ...

class Tree:
    @property
    def app_name(self) -> str: ...
    @property
    def pid(self) -> Optional[int]: ...
    @property
    def screen_size(self) -> tuple[int, int]: ...
    @property
    def nodes(self) -> list[Node]: ...
    def __len__(self) -> int: ...
    def root(self) -> Node: ...
    def parent(self, node: Node) -> Optional[Node]: ...
    def children(self, node: Node) -> list[Node]: ...
    def subtree(self, node: Node) -> list[Node]: ...
    def query(self, selector: str) -> list[Node]: ...
    def find_by_role(self, role: Role) -> list[Node]: ...
    def find_by_name(self, pattern: str) -> list[Node]: ...
    def dump(self) -> str: ...

class Provider:
    def get_tree(
        self, target: str, options: Optional[QueryOptions] = None
    ) -> Tree: ...
    def get_tree_by_pid(
        self, pid: int, options: Optional[QueryOptions] = None
    ) -> Tree: ...
    def get_all_apps(self, options: Optional[QueryOptions] = None) -> Tree: ...
    def perform_action(
        self,
        tree: Tree,
        node_index: int,
        action: Action,
        value: Optional[str] = None,
    ) -> None: ...
    def check_permissions(self) -> bool: ...
    def list_apps(self) -> list[AppInfo]: ...
    def locator(
        self,
        target: str,
        selector: str,
        options: Optional[QueryOptions] = None,
    ) -> Locator: ...

class Locator:
    @property
    def selector(self) -> str: ...
    def nth(self, n: int) -> Locator: ...
    def first(self) -> Locator: ...
    def child(self, selector: str) -> Locator: ...
    def descendant(self, selector: str) -> Locator: ...
    # Queries
    def role(self) -> Role: ...
    def name(self) -> Optional[str]: ...
    def value(self) -> Optional[str]: ...
    def description(self) -> Optional[str]: ...
    def bounds(self) -> Optional[Rect]: ...
    def states(self) -> StateSet: ...
    def numeric_value(self) -> Optional[float]: ...
    def is_visible(self) -> bool: ...
    def is_enabled(self) -> bool: ...
    def is_focused(self) -> bool: ...
    def exists(self) -> bool: ...
    def count(self) -> int: ...
    def get(self) -> Node: ...
    # Actions
    def press(self) -> None: ...
    def focus(self) -> None: ...
    def toggle(self) -> None: ...
    def select(self) -> None: ...
    def expand(self) -> None: ...
    def collapse(self) -> None: ...
    def set_value(self, value: str) -> None: ...
    def set_numeric_value(self, value: float) -> None: ...
    def increment(self) -> None: ...
    def decrement(self) -> None: ...
    def show_menu(self) -> None: ...
    def scroll_into_view(self) -> None: ...
    def type_text(self, text: str) -> None: ...
    def select_text(self, start: int, end: int) -> None: ...
    def scroll(
        self, direction: ScrollDirection, amount: float = 1.0
    ) -> None: ...
    # Waits
    def wait_visible(self, timeout_secs: float = 5.0) -> Node: ...
    def wait_attached(self, timeout_secs: float = 5.0) -> Node: ...
    def wait_detached(self, timeout_secs: float = 5.0) -> Node: ...
    def wait_enabled(self, timeout_secs: float = 5.0) -> Node: ...
    def wait_hidden(self, timeout_secs: float = 5.0) -> Node: ...

def create_provider() -> Provider: ...
